name: License Header Check

on:
  workflow_call:
    secrets:
      envGH:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check License Header
        uses: apache/skywalking-eyes@a196742f472feaffafea537ce5a2a4c3c53a8de4 # v0.9.0
        env:
            GITHUB_TOKEN: ${{ secrets.envGH }}  # needed only when you want License-Eye to comment on the pull request.
