name: Eclipse-Dash IP-Check

on:
  workflow_call:
    secrets:
      GITLAB_API_TOKEN:
        required: false

jobs:
  call-license-check:
    permissions:
      pull-requests: write
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@1c65a4dde366ffac383f3ff09332617975ac3fa6
    with:
      projectId: technology.daanse
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}
